export default function DownloadsPage() {
  return (
    <main className="bg-dark py-5">
      <div className="container px-5">
        <div className="row gx-5 align-items-center justify-content-center">
          <div className="col-8">
            <div className="my-5 text-body fw-normal">
              <h2 className="fw-bolder text-white mb-3">Downloads</h2>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img className="img-fluid rounded-3 ml-5 mb-5 float-end" src="/img/G1000_screen.jpg" width={300} alt="G1000 MFD & PFD set into a cockpit instrument panel" />
              <h5 className="text-white fw-bold">Simionic Custom Profile Manager</h5>
              <p className="text-white mb-3">
                This desktop app allows you to <b>export</b> custom profiles from your G1000 PFD app, which you can upload to the site here or exchange
                directly with other users, and <b>import</b> custom profiles downloaded from this site or obtained directly from other users.
              </p>
              <p className="text-white mb-4">
                <a href="https://youtu.be/4l4XcuoF0vo" target="_blank" rel="noopener noreferrer"><b>Watch the introductory video</b></a>
              </p>
              <p className="text-white mb-4">
                <b>Please note:</b> use of this tool is entirely at your own risk. Please ensure that you
                follow the instructions given in the introductory video to <b>backup your profile database</b> <i>before</i> using this tool.
              </p>
              <hr className="text-white" />
              <p className="text-white">
                <a href="/files/SimionicCustomProfileManager-1.0.3.zip">Download Simionic Custom Profile Manager version 1.0.3</a> - 64-bit Windows only
              </p>
              <p className="text-white-50">Version 1.0.3 - fixed broken version check. Fix bad values in profiles generated by old versions of the Simionic app.</p>
              <p className="text-white small">(Open the .ZIP file and extract the .MSI file contained inside, then double-click the .MSI file to run the installer.)</p>
              <p className="text-white-50 small">
                This software requires Microsoft .NET 6.0. If you don&apos;t have this installed,
                you can download the .NET 6.0 Runtime for Desktop Apps from{" "}
                <a href="https://dotnet.microsoft.com/en-us/download/dotnet/6.0" target="_blank" rel="noopener noreferrer">here</a>.
              </p>
              <hr className="text-white" />
              <h6 className="text-white mb-3">End of support for .NET 6.0</h6>
              <p className="text-white small">
                Support for .NET 6.0 ended in November 2024. All existing code still works fine and will continue to do so, and you can still install the
                .NET 6.0 runtime from the link above. A new version of this tool that does not require a separate installation of the .NET runtime is in
                development for a 2026 release. If you have already installed the current version, you will be prompted to upgrade when the new version is available.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
