; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Simionic Custom Profile Manager"
#define MyAppVersion "1.0.5"
#define MyAppPublisher "G1000 Profile Database"
#define MyAppURL "https://g1000profiledb.com"
#define MyAppExeName "Simionic.CustomProfiles.DesktopApp.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{02743250-74A7-4183-A8E4-854B55BBAD25}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
SetupIconFile=C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\Bokehlicia-Captiva-Accessories-text-editor.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\bz2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\e_sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\getopt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\iconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevice_id.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ideviceactivation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ideviceactivation.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicebackup.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicebackup2.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicecrashreport.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicedate.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicedebug.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicedebugserverproxy.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicediagnostics.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ideviceenterrecovery.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ideviceimagemounter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ideviceinfo.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ideviceinstaller.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicename.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicenotificationproxy.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicepair.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ideviceprovision.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicerestore.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicescreenshot.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\idevicesyslog.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\imobiledevice.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\imobiledevice-net-lighthouse.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\ios_webkit_debug_proxy.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\iproxy.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\irecovery.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\irecovery.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\libcrypto-1_1-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\libcurl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\libssl-1_1-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\libusb0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\libusb-1.0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\libxml2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\lzma.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\pcre.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\pcreposix.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\plist.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\plist_cmp.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\plist_test.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\plistutil.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\pthreadVC3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\readline.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\Simionic.Core.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\usbmuxd.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\usbmuxd.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\zip.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\projects\Simionic-G1000-CustomProfiles\src\CustomProfileManager\Simionic.CustomProfiles.DesktopApp\publish\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

